# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/final-work-2"

# 网页的标题
title: "强棒棒球少女吉瓦石露"
username: yourname
# 网站副标题
description: "我和棒球的故事"

aboutme: "我和棒球的故事"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
